Remove absurd -U__riscv__ flag in compilation with CV32
The targets using CV32 were compiled using a completely absurd -U__riscv__
flag. The result is that several regression tests were using code
targeting the OpenRISC ISA (!!!) and OR10N (!!!), roughly with 10
years of delay.
Clearly, that did not end well, resulting in errors like the following

```
  testAddSubNorm.c: Assembler messages:
  testAddSubNorm.c:116: Error: unrecognized opcode `l.addnru a2,a2,a5,5'
  testAddSubNorm.c:122: Error: unrecognized opcode `l.addnrru a2,a2,a5,5'
```

Frankly speaking, I do not have the faintest idea how such regressions
could pass using the same source, compiler, and compiler flags in the past.
But they did!!!
Bonkers..